version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - chroma
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/geospatial_db
      - REDIS_URL=redis://redis:6379
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    depends_on:
      - db
      - redis
      - chroma
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/geospatial_db
      - REDIS_URL=redis://redis:6379
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    command: celery -A backend.services.job_queue worker --loglevel=info

  db:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_DB=geospatial_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  chroma_data: